package container

import (
	"fmt"
	"strings"
)

// Dockerfile renders the Dockerfile for a canonical Selection.
//
// Layer order is the cache strategy: FROM and the shared dev profile change
// almost never, stacks change rarely, agents change most often (new pinned
// versions). Keeping agents last means a version bump only invalidates the
// agent layers, not the toolchain layers. The generated text is deterministic
// for a given Selection — Normalize sorted everything, so the same selection
// always produces the same bytes (and therefore the same content hash).
//
// Render is pure: it returns the string and an error; it never touches the
// filesystem or docker.
func Dockerfile(selection Selection) (string, error) {
	if err := selection.Validate(); err != nil {
		return "", err
	}
	if len(selection.Stacks) == 0 {
		return "", ErrNoStacks
	}
	if len(selection.Agents) == 0 {
		return "", ErrNoAgents
	}

	var b strings.Builder
	b.Grow(2048)

	fmt.Fprintf(&b, "# Generated by ai-launcher — do not edit.\nFROM %s\n", BaseImage)
	if selection.IncludeDevProfile {
		b.WriteString(DevProfile)
		b.WriteString("\n")
	}

	for _, id := range selection.Stacks {
		stack, _ := StackByID(id)
		b.WriteString("\n# Stack: ")
		b.WriteString(stack.Name)
		b.WriteString("\n")
		b.WriteString(stack.Layer)
		b.WriteString("\n")
		if stack.Helpers != "" {
			b.WriteString("\n# Stack helpers: ")
			b.WriteString(stack.Name)
			b.WriteString("\n")
			b.WriteString(stack.Helpers)
			b.WriteString("\n")
		}
	}

	// InstallConfigFile is the container path where the build context places
	// the minimal global config that names the agents to install (see
	// cmd/ai-launcher: the CLI renders it from the catalog). The Dockerfile
	// below COPYs it and runs the launcher's own installer against it, so the
	// checksum verification logic is reused byte for byte — never reimplemented
	// in shell (design C1).
	const InstallConfigFile = "/etc/ai-launch/install-config.yaml"

	for _, agent := range selection.Agents {
		b.WriteString("\n# Agent: ")
		b.WriteString(agent.Command)
		b.WriteString("\n")
		switch agent.Kind {
		case InstallRelease:
			// Design C1: the build context ships the launcher binary and a
			// minimal global config naming this agent; the RUN below invokes
			// the launcher's own installer, which resolves the pinned release,
			// verifies its checksum and extracts the binary. The comment pins
			// the version so the layer is honest and rebuildable.
			fmt.Fprintf(&b, "# installed from pinned release %s (checksum-verified)\n", agent.Version)
			b.WriteString("COPY ai-launcher /usr/local/bin/ai-launcher\n")
			b.WriteString("COPY install-config.yaml " + InstallConfigFile + "\n")
			b.WriteString("RUN ai-launcher --config " + InstallConfigFile + " --install\n")
		case InstallScript:
			if !strings.HasPrefix(agent.Script, "RUN ") {
				b.WriteString("RUN ")
			}
			b.WriteString(agent.Script)
			b.WriteString("\n")
		case InstallHostBinary:
			fmt.Fprintf(&b, "# bind-mounted from host %s at run time; not installed\n", agent.HostPath)
		}
	}

	return b.String(), nil
}

// ScriptLine normalizes an install script into a RUN line: it ensures the
// "RUN " prefix and strips a leading newline so the emitted layer is a single
// valid instruction.
func ScriptLine(script string) string {
	script = strings.TrimSpace(script)
	script = strings.TrimPrefix(script, "RUN ")
	return "RUN " + script + "\n"
}
