package container

import (
	"fmt"
	"strings"
)

// DockerfileOptions carries the launch-time toggles that change the image
// contents without being stacks or agents. The zero value renders the minimal
// image: no optional clients.
type DockerfileOptions struct {
	// DockerCLI installs the docker client (docker.io) in the image. Enable
	// it only when the launch grants the docker permission, which bind-mounts
	// the host daemon socket at run time; without that mount the client is
	// dead weight in every layer consumer.
	DockerCLI bool
	// LauncherHash identifies the ai-launcher build whose Linux binary is
	// copied into the image. It changes nothing in the rendered Dockerfile —
	// the COPY line is the same — but it belongs in the image tag: without it
	// an upgraded launcher kept hitting the image an older one built and the
	// container went on running the stale binary. Set it only when the
	// selection actually embeds the launcher, so images that never carried it
	// keep their tag.
	LauncherHash string
}

// Dockerfile renders the Dockerfile for a canonical Selection with the zero
// DockerfileOptions (the minimal image). Callers that know the launch
// permissions use DockerfileWithOptions.
//
// Render is pure: it returns the string and an error; it never touches the
// filesystem or docker.
func Dockerfile(selection Selection) (string, error) {
	return DockerfileWithOptions(selection, DockerfileOptions{})
}

// DockerfileWithOptions renders the Dockerfile for a canonical Selection.
//
// Layer order is the cache strategy: FROM and the shared dev profile change
// almost never, stacks change rarely, agents change most often (new pinned
// versions). Keeping agents last means a version bump only invalidates the
// agent layers, not the toolchain layers. The generated text is deterministic
// for a given Selection — Normalize sorted everything, so the same selection
// always produces the same bytes (and therefore the same content hash).
//
// System/toolchain layers run as root; stack helpers and agent/tool
// installers run as the least-privilege user (see the USER switches below),
// so files land with the right ownership at creation time and no recursive
// chown pass — which would duplicate gigabytes into a new layer — is needed
// at the end.
//
// Render is pure: it returns the string and an error; it never touches the
// filesystem or docker.
func DockerfileWithOptions(selection Selection, options DockerfileOptions) (string, error) {
	if err := selection.Validate(); err != nil {
		return "", err
	}
	if len(selection.Stacks) == 0 {
		return "", ErrNoStacks
	}
	if len(selection.Agents) == 0 {
		return "", ErrNoAgents
	}

	var b strings.Builder
	b.Grow(2048)

	fmt.Fprintf(&b, "# Generated by ai-launcher — do not edit.\nFROM %s\nSHELL [\"/bin/bash\", \"-o\", \"pipefail\", \"-c\"]\n", BaseImage)

	// currentUser tracks the USER of the last emitted layer so a USER
	// instruction is only written on an actual transition: root for apt and
	// toolchain managers, the least-privilege user for helpers and
	// agent/tool installers.
	currentUser := "root"
	switchUser := func(user string) {
		if currentUser == user {
			return
		}
		fmt.Fprintf(&b, "USER %s\n", user)
		currentUser = user
	}

	if selection.IncludeDevProfile {
		b.WriteString(DevProfile)
		b.WriteString("\n")
	}
	if options.DockerCLI {
		b.WriteString("\n")
		b.WriteString(DockerCLIProfile)
		b.WriteString("\n")
	}
	if selectionHasStack(selection, "java") {
		b.WriteString("ENV SDKMAN_DIR=\"/opt/sdkman\"\n")
	}
	// Create the runtime identity before the toolchain layers that chown to
	// it (NodeProfile) and before the helpers/installers that switch to it.
	b.WriteString("\n")
	b.WriteString(ContainerUserSetup)
	b.WriteString("\n")
	if selection.IncludeDevProfile && selectionNeedsNode(selection) {
		b.WriteString("\n")
		b.WriteString(NodeProfile)
		b.WriteString("\n")
	}

	for _, id := range selection.Stacks {
		stack, _ := StackByID(id)
		b.WriteString("\n# Stack: ")
		b.WriteString(stack.Name)
		b.WriteString("\n")
		// Stack toolchains install into system paths (apt, /opt, /usr/local),
		// so they stay root; the switch is a no-op for the first stack.
		switchUser("root")
		b.WriteString(stack.Layer)
		b.WriteString("\n")
		if stack.Helpers != "" {
			switchUser(ContainerUser)
			b.WriteString("\n# Stack helpers: ")
			b.WriteString(stack.Name)
			b.WriteString("\n")
			b.WriteString(stack.Helpers)
			b.WriteString("\n")
		}
	}

	// InstallConfigDir holds the minimal global config the build runs the
	// launcher's own installer against (see InstallConfigFile below). It is
	// created explicitly as root with a traversable mode: BuildKit applies
	// COPY --chmod to an implicitly created parent directory as well, which
	// left it 0644 and made the config unreadable (EACCES) to the
	// least-privilege installer — a failure the config fallback then hid.
	const installConfigDir = "/etc/ai-launch"

	// InstallConfigFile is the container path where the build context places
	// the minimal global config that names the agents to install (see
	// cmd/ai-launcher: the CLI renders it from the catalog). The Dockerfile
	// below COPYs it and runs the launcher's own installer against it, so the
	// checksum verification logic is reused byte for byte — never reimplemented
	// in shell (design C1).
	const InstallConfigFile = installConfigDir + "/install-config.yaml"

	// The install-config directory must exist with a traversable mode before
	// the COPYs below: they run after the USER switch, when it is too late to
	// fix a root-owned 0644 parent. Create it now, as root.
	if selectionNeedsInstallConfig(selection) {
		switchUser("root")
		b.WriteString("RUN install -d -m 0755 " + installConfigDir + "\n")
	}

	// Agent and tool installers run after the system/toolchain layers and as
	// the least-privilege user: everything they write under
	// /home/ai-launcher (or the user-owned npm global prefix) is owned
	// correctly at creation time, which is what makes the old final
	// `chown -R` pass unnecessary. Toolchains that must stay root-owned
	// (/opt/nvm, /opt/sdkman) are only read at run time through
	// /usr/local/bin symlinks, so their default world-traversable modes
	// suffice.
	switchUser(ContainerUser)
	for _, agent := range selection.Agents {
		b.WriteString("\n# Agent: ")
		b.WriteString(agent.Command)
		b.WriteString("\n")
		switch agent.Kind {
		case InstallRelease:
			// Design C1: the build context ships the launcher binary and a
			// minimal global config naming this agent; the RUN below invokes
			// the launcher's own installer with an explicit --agent, which
			// resolves the pinned release, verifies its checksum and extracts
			// the binary. The comment pins the version so the layer is honest
			// and rebuildable.
			fmt.Fprintf(&b, "# installed from pinned release %s (checksum-verified)\n", agent.Version)
			b.WriteString(dockerfileLauncherCopy)
			b.WriteString(configCopyLine(InstallConfigFile))
			fmt.Fprintf(&b, "RUN ai-launcher --config %s --install --agent %s\n", InstallConfigFile, agent.Command)
			fmt.Fprintf(&b, "RUN command -v %s >/dev/null\n", shellQuoteWord(agent.Command))
		case InstallScript:
			b.WriteString(ScriptLine(agent))
			fmt.Fprintf(&b, "RUN command -v %s >/dev/null\n", shellQuoteWord(agent.Command))
		case InstallNpm:
			// npm-distributed agents install globally; the NodeProfile already
			// put the nvm node bin dir on PATH and handed the global prefix to
			// this user, so the CLI lands runnable and owned correctly. The
			// download cache is cleaned so it does not bloat the layer.
			fmt.Fprintf(&b, "# npm package %s\n", agent.NpmPackage)
			fmt.Fprintf(&b, "RUN npm install -g %s && npm cache clean --force\n", agent.NpmPackage)
			fmt.Fprintf(&b, "RUN command -v %s >/dev/null\n", shellQuoteWord(agent.Command))
		case InstallHostBinary:
			fmt.Fprintf(&b, "# bind-mounted from host %s at run time; not installed\n", agent.HostPath)
		}
	}
	for _, tool := range selection.Tools {
		b.WriteString("\n# Tool: ")
		b.WriteString(tool.Command)
		b.WriteString("\n")
		if tool.Kind != InstallRelease || tool.Release == nil {
			return "", fmt.Errorf("tool %q has no supported release recipe", tool.Command)
		}
		fmt.Fprintf(&b, "# installed from pinned release %s (checksum-verified)\n", tool.Version)
		b.WriteString(dockerfileLauncherCopy)
		b.WriteString(configCopyLine(InstallConfigFile))
		fmt.Fprintf(&b, "RUN ai-launcher --config %s --install --agent %s\n", InstallConfigFile, tool.Command)
		fmt.Fprintf(&b, "RUN command -v %s >/dev/null\n", shellQuoteWord(tool.Command))
	}
	if SelectionNeedsMemory(selection) {
		// A memory-enabled harness must not rely on a host-side ai-memory
		// wrapper being present in the image. Install it through the same
		// checksum-verified launcher path used for release agents and fail the
		// build immediately when the command is still absent.
		b.WriteString("\n# Tool: ai-memory\n")
		b.WriteString(dockerfileLauncherCopy)
		b.WriteString(configCopyLine(InstallConfigFile))
		b.WriteString("RUN ai-launcher --config " + InstallConfigFile + " --install --agent ai-memory\n")
		b.WriteString("RUN command -v ai-memory >/dev/null\n")
	}

	// Agent containers are short-lived interactive processes rather than
	// long-running services; make that lifecycle explicit for image scanners
	// and operators instead of pretending a service probe would be meaningful.
	b.WriteString("HEALTHCHECK NONE\n")
	// The image entrypoint always runs as the least-privilege user, even when
	// nothing above needed the switch (e.g. host-binary-only agents).
	fmt.Fprintf(&b, "USER %s\n", ContainerUser)

	return b.String(), nil
}

// configCopyLine renders the install-config COPY with an explicit readable
// mode: the build context writes the config 0600 and COPY preserves modes,
// but the in-image installer now runs as the least-privilege user and must be
// able to read it.
func configCopyLine(installConfigFile string) string {
	return strings.Replace(dockerfileConfigCopy, "COPY ", "COPY --chmod=0644 ", 1) + installConfigFile + "\n"
}

// selectionNeedsInstallConfig reports whether the build reads InstallConfigFile
// at all: release-installed agents and tools resolve their pins through it,
// and a memory-enabled selection installs ai-memory the same way. Script/npm
// agents and host-binary mounts never touch it.
func selectionNeedsInstallConfig(selection Selection) bool {
	if SelectionNeedsMemory(selection) {
		return true
	}
	for _, agent := range selection.Agents {
		if agent.Kind == InstallRelease {
			return true
		}
	}
	return len(selection.Tools) > 0
}

func selectionHasStack(selection Selection, id string) bool {
	for _, selected := range selection.Stacks {
		if selected == id {
			return true
		}
	}
	return false
}

func selectionNeedsNode(selection Selection) bool {
	if selectionHasStack(selection, "node") {
		return true
	}
	for _, agent := range selection.Agents {
		if agent.Kind == InstallNpm || agent.NeedsNode {
			return true
		}
	}
	return false
}

// ScriptLine normalizes an install script into a RUN line: it ensures the
// "RUN " prefix and strips a leading newline so the emitted layer is a single
// valid instruction. When the install's post-install step opens an interactive
// login (AllowSetupFailure), a non-zero installer status is accepted only
// when the requested executable is present afterwards.
func ScriptLine(agent AgentInstall) string {
	script := strings.TrimSpace(agent.Script)
	script = strings.TrimPrefix(script, "RUN ")
	if agent.AllowSetupFailure {
		script = "set +e; " + script + "; status=$?; set -e; if test \"$status\" -ne 0 && ! command -v " + shellQuoteWord(agent.Command) + " >/dev/null 2>&1; then exit \"$status\"; fi; exit 0"
	}
	return "RUN " + script + "\n"
}

func shellQuoteWord(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
