package container

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	// EgressProxyServiceID is the Compose service name for the injected
	// egress-allowlist proxy — never selectable from the Services catalog,
	// only auto-injected by internal/launcher's BuildCompose.
	EgressProxyServiceID = "egress-proxy"
	// EgressProxyPort is the proxy's listening port, used both inside the
	// generated squid.conf and in the HTTP_PROXY/HTTPS_PROXY URL injected
	// into the agent's environment.
	EgressProxyPort = 3128
	// EgressProxyImage is the pinned proxy image, pinned by digest rather
	// than tag: Canonical's ubuntu/squid Docker Hub repo does not publish a
	// tag outside "latest"/"edge"/"*_beta" — and the "6.6-24.04_beta" tag
	// this used to be pinned to is itself misleading (the image running
	// under it reports "Squid Cache: Version 6.13", not 6.6). A tag with
	// that mismatch, on a floating beta channel, gives zero reproducibility
	// for the one component whose entire job is enforcing egress policy.
	// Verified directly: `docker pull` this digest, `docker manifest
	// inspect ubuntu/squid:6.6-24.04_beta` to re-resolve if it ever needs
	// bumping.
	EgressProxyImage = "ubuntu/squid@sha256:6a097f68bae708cedbabd6188d68c7e2e7a38cedd05a176e1cc0ba29e3bbe029"
)

// egressDomainPattern is an allowlist, not a denylist, for hostname shape: an
// optional leading "." (squid's own explicit-subdomain-wildcard notation,
// e.g. ".npmjs.org" — GenerateEgressProxyConfig also auto-prefixes a bare
// domain the same way, so both spellings are accepted as equivalent), then
// at least two labels of 1-63 chars of letters/digits/hyphens each (never
// leading or trailing with a hyphen). A character-denylist approach (reject
// known-bad chars) was tried first and caught real injection attempts, but
// independent review found it silently let through non-hostnames that still
// parse as valid squid ACL entries — most importantly a bare TLD like "com",
// which as a dstdomain ACL matches (and thus allows egress to) every ".com"
// domain on the internet, the opposite of what "allowed domain: com" would
// look like it means. Requiring ≥2 labels rejects that; the character class
// rejects "*", "..", "/", ":", and non-ASCII/IDN homograph tricks
// (punycode-encode if genuinely needed).
var egressDomainPattern = regexp.MustCompile(
	`^\.?[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$`,
)

// EgressProxyConfigPath returns the host path where the generated squid.conf
// for this project is written and mounted read-only into the proxy
// container. Pure — no I/O. Mirrors the internal/container/services.go
// .ai-launcher/data/<service>/ convention without going through
// persistentServiceVolumes (that helper resolves a directory mount; this is
// a single file).
func EgressProxyConfigPath(dataDir string) string {
	return filepath.Join(dataDir, EgressProxyServiceID, "squid.conf")
}

// ValidateEgressDomains rejects an empty list and any entry that isn't a
// plausible multi-label hostname per egressDomainPattern — see its comment
// for why an allowlist regex replaced an earlier denylist-of-bad-characters
// approach (defense against config injection: a domain string here becomes
// a raw line in a file mounted into a container, so malformed input is
// rejected outright rather than partially sanitized).
func ValidateEgressDomains(domains []string) error {
	if len(domains) == 0 {
		return fmt.Errorf("at least one allowed domain is required")
	}
	for _, domain := range domains {
		trimmed := strings.TrimSpace(domain)
		if !egressDomainPattern.MatchString(trimmed) {
			return fmt.Errorf("allowed domain %q is not a valid hostname (need at least two labels, letters/digits/hyphens only)", domain)
		}
	}
	return nil
}

// GenerateEgressProxyConfig renders a complete squid.conf that allows
// outbound HTTP/HTTPS only to the given domains (and their subdomains) and
// denies everything else. Pure — same input order always produces the same
// output; domains are emitted in the order given (no map iteration).
func GenerateEgressProxyConfig(domains []string) (string, error) {
	if err := ValidateEgressDomains(domains); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Generated by ai-launcher — do not edit by hand.\n")
	fmt.Fprintf(&b, "http_port %d\n\n", EgressProxyPort)

	b.WriteString("acl SSL_ports port 443\n")
	b.WriteString("acl Safe_ports port 80\n")
	b.WriteString("acl Safe_ports port 443\n")
	b.WriteString("acl CONNECT method CONNECT\n\n")

	for _, domain := range domains {
		trimmed := strings.TrimSpace(domain)
		if !strings.HasPrefix(trimmed, ".") {
			trimmed = "." + trimmed
		}
		fmt.Fprintf(&b, "acl allowed_dst dstdomain %s\n", trimmed)
	}
	b.WriteString("\n")

	b.WriteString("http_access deny !Safe_ports\n")
	b.WriteString("http_access deny CONNECT !SSL_ports\n")
	b.WriteString("http_access allow allowed_dst\n")
	b.WriteString("http_access deny all\n\n")

	b.WriteString("cache deny all\n")

	return b.String(), nil
}

// EgressProxyComposeService builds the proxy's Compose service. It is the
// only service dual-homed across the internal (agent-facing) network and the
// egress (real-internet) network; every other service, including the agent,
// stays on internalNetwork only.
func EgressProxyComposeService(configPath, internalNetwork, egressNetwork string) (ComposeService, error) {
	if strings.TrimSpace(configPath) == "" {
		return ComposeService{}, fmt.Errorf("egress proxy config path is required")
	}
	if strings.TrimSpace(internalNetwork) == "" {
		return ComposeService{}, fmt.Errorf("egress proxy internal network is required")
	}
	if strings.TrimSpace(egressNetwork) == "" {
		return ComposeService{}, fmt.Errorf("egress proxy egress network is required")
	}
	capDrop, securityOpt := hardenedServiceSecurity()
	return ComposeService{
		Image:    EgressProxyImage,
		Volumes:  []string{configPath + ":/etc/squid/squid.conf:ro"},
		Networks: []string{internalNetwork, egressNetwork},
		// "no" matches every other generated service (ComposeServiceFromCatalog,
		// ComposeServiceFromRunConfig) — this project does not run compose
		// stacks as durable background services, so auto-restart has no
		// established convention here to diverge from.
		Restart: "no",
		// The squid daemon starts as root and drops to its unprivileged "proxy"
		// user via setgid/setuid, so cap_drop ALL alone (the baseline every
		// service carries) removes CAP_SETGID/CAP_SETUID and the daemon aborts
		// before it can serve a single request — caught by the behavioral
		// integration test. cap_add hands back exactly those two, nothing else:
		// every other capability (NET_ADMIN, SYS_ADMIN, …) stays dropped.
		// read_only is intentionally NOT set: squid writes its pid/socket/cache
		// state under /run and /var/spool/squid.
		CapDrop:     capDrop,
		CapAdd:      []string{"SETGID", "SETUID"},
		SecurityOpt: securityOpt,
		Healthcheck: map[string]any{
			// squidclient is NOT present in the ubuntu/squid image (verified
			// against the running container — a prior version of this
			// healthcheck used it and never once passed). "squid -k check"
			// is squid's own built-in self-check subcommand, shipped in the
			// same binary that runs the daemon, so it's always available:
			// it validates the running instance's config/PID without
			// needing any extra tooling in the image.
			"test": []string{composeHealthcheckShell, "squid -k check"},
		},
	}, nil
}

// ParseEgressDomains splits a comma-separated domain list (the TUI's
// single-line text-input form) into a validated slice. Empty pieces from
// leading/trailing/doubled commas are dropped before validation. An
// empty/whitespace-only value returns (nil, nil) — the TUI's "field
// cleared" case, not an error.
func ParseEgressDomains(value string) ([]string, error) {
	if strings.TrimSpace(value) == "" {
		return nil, nil
	}
	var domains []string
	for _, part := range strings.Split(value, ",") {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		domains = append(domains, trimmed)
	}
	if len(domains) == 0 {
		return nil, nil
	}
	if err := ValidateEgressDomains(domains); err != nil {
		return nil, err
	}
	return domains, nil
}
