package container

import (
	"fmt"
	"path/filepath"
	"strings"
)

const (
	// EgressProxyServiceID is the Compose service name for the injected
	// egress-allowlist proxy — never selectable from the Services catalog,
	// only auto-injected by internal/launcher's BuildCompose.
	EgressProxyServiceID = "egress-proxy"
	// EgressProxyPort is the proxy's listening port, used both inside the
	// generated squid.conf and in the HTTP_PROXY/HTTPS_PROXY URL injected
	// into the agent's environment.
	EgressProxyPort = 3128
	// EgressProxyImage is the pinned proxy image.
	//
	// TODO(security): confirm the current stable tag before merge. Canonical's
	// ubuntu/squid Docker Hub repo does not currently publish a tag outside
	// "latest"/"edge"/"*_beta" — 6.6-24.04_beta was the most specific
	// (squid 6.6, Ubuntu 24.04) available at the time this was written, but it
	// is still a beta channel, not a released-stable one. Re-verify against
	// https://hub.docker.com/r/ubuntu/squid/tags before this ships.
	EgressProxyImage = "ubuntu/squid:6.6-24.04_beta"
)

// egressDomainInjectionChars are rejected in a domain because each one can
// break out of the single ACL line the domain is emitted into, or has no
// legitimate place in a hostname.
const egressDomainInjectionChars = " \t\r\n#\"';"

// EgressProxyConfigPath returns the host path where the generated squid.conf
// for this project is written and mounted read-only into the proxy
// container. Pure — no I/O. Mirrors the internal/container/services.go
// .ai-launcher/data/<service>/ convention without going through
// persistentServiceVolumes (that helper resolves a directory mount; this is
// a single file).
func EgressProxyConfigPath(dataDir string) string {
	return filepath.Join(dataDir, EgressProxyServiceID, "squid.conf")
}

// ValidateEgressDomains rejects an empty list and any entry that is empty,
// whitespace-only, or contains a character that could break out of a single
// squid ACL line in the generated config (defense against config injection —
// a domain string here becomes a raw line in a file mounted into a
// container).
func ValidateEgressDomains(domains []string) error {
	if len(domains) == 0 {
		return fmt.Errorf("at least one allowed domain is required")
	}
	for _, domain := range domains {
		trimmed := strings.TrimSpace(domain)
		if trimmed == "" {
			return fmt.Errorf("allowed domain entry is empty")
		}
		if strings.ContainsAny(trimmed, egressDomainInjectionChars) {
			return fmt.Errorf("allowed domain %q contains a disallowed character", domain)
		}
	}
	return nil
}

// GenerateEgressProxyConfig renders a complete squid.conf that allows
// outbound HTTP/HTTPS only to the given domains (and their subdomains) and
// denies everything else. Pure — same input order always produces the same
// output; domains are emitted in the order given (no map iteration).
func GenerateEgressProxyConfig(domains []string) (string, error) {
	if err := ValidateEgressDomains(domains); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Generated by ai-launcher — do not edit by hand.\n")
	fmt.Fprintf(&b, "http_port %d\n\n", EgressProxyPort)

	b.WriteString("acl SSL_ports port 443\n")
	b.WriteString("acl Safe_ports port 80\n")
	b.WriteString("acl Safe_ports port 443\n")
	b.WriteString("acl CONNECT method CONNECT\n\n")

	for _, domain := range domains {
		trimmed := strings.TrimSpace(domain)
		if !strings.HasPrefix(trimmed, ".") {
			trimmed = "." + trimmed
		}
		fmt.Fprintf(&b, "acl allowed_dst dstdomain %s\n", trimmed)
	}
	b.WriteString("\n")

	b.WriteString("http_access deny !Safe_ports\n")
	b.WriteString("http_access deny CONNECT !SSL_ports\n")
	b.WriteString("http_access allow allowed_dst\n")
	b.WriteString("http_access deny all\n\n")

	b.WriteString("cache deny all\n")

	return b.String(), nil
}

// EgressProxyComposeService builds the proxy's Compose service. It is the
// only service dual-homed across the internal (agent-facing) network and the
// egress (real-internet) network; every other service, including the agent,
// stays on internalNetwork only.
func EgressProxyComposeService(configPath, internalNetwork, egressNetwork string) (ComposeService, error) {
	if strings.TrimSpace(configPath) == "" {
		return ComposeService{}, fmt.Errorf("egress proxy config path is required")
	}
	if strings.TrimSpace(internalNetwork) == "" {
		return ComposeService{}, fmt.Errorf("egress proxy internal network is required")
	}
	if strings.TrimSpace(egressNetwork) == "" {
		return ComposeService{}, fmt.Errorf("egress proxy egress network is required")
	}
	return ComposeService{
		Image:    EgressProxyImage,
		Volumes:  []string{configPath + ":/etc/squid/squid.conf:ro"},
		Networks: []string{internalNetwork, egressNetwork},
		// "no" matches every other generated service (ComposeServiceFromCatalog,
		// ComposeServiceFromRunConfig) — this project does not run compose
		// stacks as durable background services, so auto-restart has no
		// established convention here to diverge from.
		Restart: "no",
		Healthcheck: map[string]any{
			// squidclient ships with the squid package (present in ubuntu/squid);
			// mgr:info is squid's own cache-manager status report, so this
			// confirms the proxy process is actually accepting requests, not
			// just that the port is open.
			"test": []string{composeHealthcheckShell,
				fmt.Sprintf("squidclient -h localhost -p %d mgr:info >/dev/null 2>&1", EgressProxyPort)},
		},
	}, nil
}

// ParseEgressDomains splits a comma-separated domain list (the TUI's
// single-line text-input form) into a validated slice. Empty pieces from
// leading/trailing/doubled commas are dropped before validation. An
// empty/whitespace-only value returns (nil, nil) — the TUI's "field
// cleared" case, not an error.
func ParseEgressDomains(value string) ([]string, error) {
	if strings.TrimSpace(value) == "" {
		return nil, nil
	}
	var domains []string
	for _, part := range strings.Split(value, ",") {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		domains = append(domains, trimmed)
	}
	if len(domains) == 0 {
		return nil, nil
	}
	if err := ValidateEgressDomains(domains); err != nil {
		return nil, err
	}
	return domains, nil
}
